# Form implementation generated from reading ui file 'Flashcard/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 365)
        MainWindow.setMinimumSize(QtCore.QSize(696, 365))
        MainWindow.setMaximumSize(QtCore.QSize(696, 365))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel { background:transparent; color:black; font-size:18px; font-weight:700; border:none; }")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Flashcard\\pics/images.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(229, 60, 251, 241))
        self.frame.setStyleSheet("QFrame{background-color: #EAEAEA;\n"
"border-radius: 15px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 251, 151))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: white;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pic = QtWidgets.QLabel(parent=self.frame_2)
        self.pic.setGeometry(QtCore.QRect(0, 0, 251, 151))
        self.pic.setStyleSheet("QFrame {border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"\n"
"}")
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("Flashcard\\../../../../../Users/admin/Pictures/Hazz\'s pic/Untitled design.png"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.label_definition1 = QtWidgets.QLabel(parent=self.frame)
        self.label_definition1.setGeometry(QtCore.QRect(0, 160, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_definition1.setFont(font)
        self.label_definition1.setStyleSheet("QLabel { background:transparent; color:black; font-size:15px; font-weight:700; border:none; }")
        self.label_definition1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_definition1.setObjectName("label_definition1")
        self.label_phienam = QtWidgets.QLabel(parent=self.frame)
        self.label_phienam.setGeometry(QtCore.QRect(0, 190, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.label_phienam.setFont(font)
        self.label_phienam.setStyleSheet("QLabel { background:transparent; color:black; font-size:12px; font-weight:500; border:none; }")
        self.label_phienam.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_phienam.setObjectName("label_phienam")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Flashcard\\pics/images (1).jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(36, 32))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.frame_3.setStyleSheet("QFrame{background-color: #EAEAEA;\n"
"border-radius: 15px;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius:0px\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(36, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 50, 251, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_definitionTV = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_definitionTV.setFont(font)
        self.label_definitionTV.setStyleSheet("QLabel { background:transparent; color:#34c759; font-size:15px; font-weight:700; border:none; }")
        self.label_definitionTV.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_definitionTV.setObjectName("label_definitionTV")
        self.verticalLayout.addWidget(self.label_definitionTV)
        self.label_definition2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_definition2.setFont(font)
        self.label_definition2.setStyleSheet("QLabel { background:transparent; color:black; font-size:15px; font-weight:700; border:none; }")
        self.label_definition2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_definition2.setObjectName("label_definition2")
        self.verticalLayout.addWidget(self.label_definition2)
        self.label_phienam2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.label_phienam2.setFont(font)
        self.label_phienam2.setStyleSheet("QLabel { background:transparent; color:black; font-size:12px; font-weight:500; border:none; }")
        self.label_phienam2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_phienam2.setObjectName("label_phienam2")
        self.verticalLayout.addWidget(self.label_phienam2)
        self.label_ex = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label_ex.setFont(font)
        self.label_ex.setStyleSheet("QLabel { background:transparent; color:black; font-size:8px; font-weight:400; border:none; }")
        self.label_ex.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ex.setObjectName("label_ex")
        self.verticalLayout.addWidget(self.label_ex)
        self.layoutWidget.raise_()
        self.pushButton_3.raise_()
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Flashcard\\../../../../M3M english/images.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.button_continue_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_continue_2.setGeometry(QtCore.QRect(360, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.button_continue_2.setFont(font)
        self.button_continue_2.setStyleSheet("\n"
"        QPushButton { background:#22c55e; border-radius:8px; color:white; font-size:9px; font-weight:700; }\n"
"        QPushButton:hover { background:#16a34a; }\n"
"        QPushButton:pressed { background:#15803d; }\n"
"       ")
        self.button_continue_2.setObjectName("button_continue_2")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(230, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.button_back.setFont(font)
        self.button_back.setStyleSheet("\n"
"        QPushButton { background:#22c55e; border-radius:8px; color:white; font-size:9px; font-weight:700; }\n"
"        QPushButton:hover { background:#16a34a; }\n"
"        QPushButton:pressed { background:#15803d; }\n"
"       ")
        self.button_back.setObjectName("button_back")
        self.button_back_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back_2.setGeometry(QtCore.QRect(220, 50, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.button_back_2.setFont(font)
        self.button_back_2.setStyleSheet("\n"
"        QPushButton { background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(155, 255, 153, 157), stop:0.801136 rgba(205, 220, 57, 160), stop:0.994318 rgba(220, 220, 220, 153)); border-radius:8px; color:white; font-size:9px; font-weight:700; }\n"
"        QPushButton:hover { background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(118, 194, 116, 192), stop:0.801136 rgba(177, 190, 49, 201), stop:0.971591 rgba(190, 190, 190, 195)); }\n"
"        QPushButton:pressed { background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(118, 194, 116, 192), stop:0.801136 rgba(177, 190, 49, 201), stop:0.971591 rgba(190, 190, 190, 195)); }\n"
"       ")
        self.button_back_2.setObjectName("button_back_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Topic: Travel & Culture"))
        self.label_definition1.setText(_translate("MainWindow", "Breathtaking"))
        self.label_phienam.setText(_translate("MainWindow", "/ˈbreθˌteɪ.kɪŋ/"))
        self.label_definitionTV.setText(_translate("MainWindow", "Đẹp vãi"))
        self.label_definition2.setText(_translate("MainWindow", "Breathtaking"))
        self.label_phienam2.setText(_translate("MainWindow", "/aɪˈtɪn.ə.rer.i/"))
        self.label_ex.setText(_translate("MainWindow", "Eg: The view from the mountain was breathtaking."))
        self.button_continue_2.setText(_translate("MainWindow", "▶"))
        self.button_back.setText(_translate("MainWindow", "◀ "))
        self.button_back_2.setText(_translate("MainWindow", "🔊"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
