# Form implementation generated from reading ui file 'Login_v3.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 630)
        MainWindow.setMinimumSize(QtCore.QSize(800, 560))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 780))
        MainWindow.setStyleSheet("QMainWindow { background-color: white; }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left.sizePolicy().hasHeightForWidth())
        self.frame_left.setSizePolicy(sizePolicy)
        self.frame_left.setStyleSheet("QFrame#frame_left {\n"
"    background: qlineargradient(x1:0,y1:0,x2:0.3,y2:1,\n"
"        stop:0 #c6db2e, stop:1 #4caf50);\n"
"    border: none;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.label_mascot = QtWidgets.QLabel(parent=self.frame_left)
        # Chỉnh lại tọa độ x, y và thu nhỏ kích thước (width=180, height=200)
        self.label_mascot.setGeometry(QtCore.QRect(120, 130, 180, 200))
        self.label_mascot.setStyleSheet("QLabel{background:transparent;border:none;}")
        self.label_mascot.setText("")
        # Cập nhật đường dẫn trỏ tới file khủng long
        self.label_mascot.setPixmap(QtGui.QPixmap("trang_tri/images/dino.png"))
        self.label_mascot.setScaledContents(True)
        self.label_mascot.setObjectName("label_mascot")
        self.circle_1 = QtWidgets.QFrame(parent=self.frame_left)
        self.circle_1.setGeometry(QtCore.QRect(28, 180, 90, 90))
        self.circle_1.setStyleSheet("QFrame{background:#2e7d32;border-radius:45px;border:none;}")
        self.circle_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circle_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_1.setObjectName("circle_1")
        self.circle_2 = QtWidgets.QFrame(parent=self.frame_left)
        self.circle_2.setGeometry(QtCore.QRect(320, 290, 70, 70))
        self.circle_2.setStyleSheet("QFrame{background:#388e3c;border-radius:35px;border:none;}")
        self.circle_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circle_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_2.setObjectName("circle_2")
        self.circle_3 = QtWidgets.QFrame(parent=self.frame_left)
        self.circle_3.setGeometry(QtCore.QRect(35, 430, 80, 80))
        self.circle_3.setStyleSheet("QFrame{background:#1B5E20;border-radius:40px;border:none;}")
        self.circle_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circle_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_3.setObjectName("circle_3")
        self.circle_4 = QtWidgets.QFrame(parent=self.frame_left)
        self.circle_4.setGeometry(QtCore.QRect(310, 430, 100, 100))
        self.circle_4.setStyleSheet("QFrame{background:#1B5E20;border-radius:50px;border:none;}")
        self.circle_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circle_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_4.setObjectName("circle_4")
        self.label_title_left = QtWidgets.QLabel(parent=self.frame_left)
        self.label_title_left.setGeometry(QtCore.QRect(60, 300, 300, 55))
        self.label_title_left.setStyleSheet("QLabel{color:white;font-size:30px;font-weight:800;background:transparent;border:none;}")
        self.label_title_left.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title_left.setObjectName("label_title_left")
        self.frame_card = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_card.setGeometry(QtCore.QRect(55, 365, 300, 95))
        self.frame_card.setStyleSheet("QFrame#frame_card{background:white;border-radius:16px;border:none;}")
        self.frame_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_card.setObjectName("frame_card")
        self.label_tagline = QtWidgets.QLabel(parent=self.frame_card)
        self.label_tagline.setGeometry(QtCore.QRect(10, 10, 280, 75))
        self.label_tagline.setStyleSheet("QLabel{background:transparent;border:none;}")
        self.label_tagline.setObjectName("label_tagline")
        self.label = QtWidgets.QLabel(parent=self.frame_left)
        self.label.setGeometry(QtCore.QRect(0, 80, 471, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../Users/admin/Pictures/my pic/hihi.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_mascot.raise_()
        self.circle_1.raise_()
        self.circle_2.raise_()
        self.circle_3.raise_()
        self.circle_4.raise_()
        self.label_title_left.raise_()
        self.frame_card.raise_()
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_right.sizePolicy().hasHeightForWidth())
        self.frame_right.setSizePolicy(sizePolicy)
        self.frame_right.setStyleSheet("QFrame#frame_right{background:white;border:none;}")
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.layoutWidget_right = QtWidgets.QWidget(parent=self.frame_right)
        self.layoutWidget_right.setGeometry(QtCore.QRect(30, 20, 390, 1055))
        self.layoutWidget_right.setObjectName("layoutWidget_right")
        self.vLayout_right = QtWidgets.QVBoxLayout(self.layoutWidget_right)
        self.vLayout_right.setContentsMargins(8, 8, 8, 8)
        self.vLayout_right.setSpacing(5)
        self.vLayout_right.setObjectName("vLayout_right")
        self.label_M3M = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_M3M.setStyleSheet("QLabel{\n"
"    color:qlineargradient(spread:pad,x1:0.455,y1:0,x2:0.455,y2:1,\n"
"        stop:0 rgba(205,220,57,255),stop:0.75 rgba(205,220,57,255),\n"
"        stop:1 rgba(174,213,129,255));\n"
"    font-size:36px;font-weight:800;background:transparent;border:none;\n"
"    padding-bottom:0px;\n"
"}")
        self.label_M3M.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_M3M.setObjectName("label_M3M")
        self.vLayout_right.addWidget(self.label_M3M)
        self.label_English = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_English.setStyleSheet("QLabel{\n"
"    color:#4CAF50;font-size:36px;font-weight:800;\n"
"    background:transparent;border:none;margin-top:-12px;\n"
"}")
        self.label_English.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_English.setObjectName("label_English")
        self.vLayout_right.addWidget(self.label_English)
        self.frame_tabs = QtWidgets.QFrame(parent=self.layoutWidget_right)
        self.frame_tabs.setMinimumSize(QtCore.QSize(0, 38))
        self.frame_tabs.setMaximumSize(QtCore.QSize(16777215, 38))
        self.frame_tabs.setStyleSheet("QFrame#frame_tabs{\n"
"    background:#e8e8e8;\n"
"    border-radius:10px;\n"
"    border:none;\n"
"}")
        self.frame_tabs.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tabs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tabs.setObjectName("frame_tabs")
        self.btn_Signup = QtWidgets.QPushButton(parent=self.frame_tabs)
        self.btn_Signup.setGeometry(QtCore.QRect(195, 4, 171, 32))
        self.btn_Signup.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_Signup.setStyleSheet("QPushButton{\n"
"    background:transparent;color:#a259ff;\n"
"    border-radius:8px;font-weight:bold;font-size:13px;border:none;\n"
"}\n"
"QPushButton:hover{background:#d8d8d8;}")
        self.btn_Signup.setObjectName("btn_Signup")
        self.btn_Login = QtWidgets.QPushButton(parent=self.frame_tabs)
        self.btn_Login.setGeometry(QtCore.QRect(4, 4, 191, 32))
        self.btn_Login.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_Login.setStyleSheet("QPushButton{\n"
"    background:#34C759;color:white;\n"
"    border-radius:8px;font-weight:bold;font-size:13px;border:none;\n"
"}\n"
"QPushButton:hover{background:#2db34e;}")
        self.btn_Login.setObjectName("btn_Login")
        self.vLayout_right.addWidget(self.frame_tabs)
        spacerItem = QtWidgets.QSpacerItem(0, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.vLayout_right.addItem(spacerItem)
        self.label_username = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_username.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_username.setObjectName("label_username")
        self.vLayout_right.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.layoutWidget_right)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 38))
        self.lineEdit_username.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.vLayout_right.addWidget(self.lineEdit_username)
        self.hLayout_emailRow = QtWidgets.QHBoxLayout()
        self.hLayout_emailRow.setObjectName("hLayout_emailRow")
        self.label_email = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_email.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_email.setObjectName("label_email")
        self.hLayout_emailRow.addWidget(self.label_email)
        self.noti_email = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.noti_email.setStyleSheet("QLabel{color:#e53935;font-size:11px;background:transparent;border:none;}")
        self.noti_email.setText("")
        self.noti_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.noti_email.setObjectName("noti_email")
        self.hLayout_emailRow.addWidget(self.noti_email)
        self.vLayout_right.addLayout(self.hLayout_emailRow)
        self.enter_email = QtWidgets.QLineEdit(parent=self.layoutWidget_right)
        self.enter_email.setMinimumSize(QtCore.QSize(0, 38))
        self.enter_email.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.enter_email.setObjectName("enter_email")
        self.vLayout_right.addWidget(self.enter_email)
        self.hLayout_pwRow = QtWidgets.QHBoxLayout()
        self.hLayout_pwRow.setObjectName("hLayout_pwRow")
        self.label_password = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_password.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_password.setObjectName("label_password")
        self.hLayout_pwRow.addWidget(self.label_password)
        self.noti_password = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.noti_password.setStyleSheet("QLabel{color:#e53935;font-size:11px;background:transparent;border:none;}")
        self.noti_password.setText("")
        self.noti_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.noti_password.setObjectName("noti_password")
        self.hLayout_pwRow.addWidget(self.noti_password)
        self.vLayout_right.addLayout(self.hLayout_pwRow)
        self.enter_password = QtWidgets.QLineEdit(parent=self.layoutWidget_right)
        self.enter_password.setMinimumSize(QtCore.QSize(0, 38))
        self.enter_password.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.enter_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.enter_password.setObjectName("enter_password")
        self.vLayout_right.addWidget(self.enter_password)
        self.label_forgot = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_forgot.setStyleSheet("QLabel{\n"
"    color:#34C759;font-size:11px;background:transparent;\n"
"    border:none;font-weight:bold;\n"
"}")
        self.label_forgot.setText("")
        self.label_forgot.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_forgot.setObjectName("label_forgot")
        self.vLayout_right.addWidget(self.label_forgot)
        self.noti_general = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.noti_general.setStyleSheet("QLabel{\n"
"    color:#e53935;font-size:11px;background:transparent;\n"
"    border:none;\n"
"}")
        self.noti_general.setText("")
        self.noti_general.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.noti_general.setObjectName("noti_general")
        self.vLayout_right.addWidget(self.noti_general)
        self.btnLogin_Enter = QtWidgets.QPushButton(parent=self.layoutWidget_right)
        self.btnLogin_Enter.setMinimumSize(QtCore.QSize(0, 40))
        self.btnLogin_Enter.setStyleSheet("QPushButton{\n"
"    background:#34C759;color:white;border-radius:8px;\n"
"    font-weight:bold;font-size:15px;border:none;\n"
"}\n"
"QPushButton:hover{background:#2db34e;}\n"
"QPushButton:pressed{background:#259e45;}")
        self.btnLogin_Enter.setObjectName("btnLogin_Enter")
        self.vLayout_right.addWidget(self.btnLogin_Enter)
        self.label_firsttime_full = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_firsttime_full.setStyleSheet("QLabel{font-size:12px;background:transparent;border:none;color:#444;}")
        self.label_firsttime_full.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_firsttime_full.setObjectName("label_firsttime_full")
        self.vLayout_right.addWidget(self.label_firsttime_full)
        self.hLayout_or = QtWidgets.QHBoxLayout()
        self.hLayout_or.setObjectName("hLayout_or")
        self.line_left = QtWidgets.QFrame(parent=self.layoutWidget_right)
        self.line_left.setStyleSheet("QFrame{color:#ccc;border:none;}")
        self.line_left.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_left.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_left.setObjectName("line_left")
        self.hLayout_or.addWidget(self.line_left)
        self.label_or = QtWidgets.QLabel(parent=self.layoutWidget_right)
        self.label_or.setStyleSheet("QLabel{color:#888;font-size:12px;padding:0 8px;background:transparent;border:none;}")
        self.label_or.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_or.setObjectName("label_or")
        self.hLayout_or.addWidget(self.label_or)
        self.line_right = QtWidgets.QFrame(parent=self.layoutWidget_right)
        self.line_right.setStyleSheet("QFrame{color:#ccc;border:none;}")
        self.line_right.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_right.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_right.setObjectName("line_right")
        self.hLayout_or.addWidget(self.line_right)
        self.vLayout_right.addLayout(self.hLayout_or)
        self.login_gg = QtWidgets.QPushButton(parent=self.layoutWidget_right)
        self.login_gg.setMinimumSize(QtCore.QSize(0, 38))
        self.login_gg.setStyleSheet("QPushButton{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:5px;background:white;font-size:13px;color:#333;\n"
"}\n"
"QPushButton:hover{background:#fffbf0;}")
        self.login_gg.setObjectName("login_gg")
        self.vLayout_right.addWidget(self.login_gg)
        self.login_fb = QtWidgets.QPushButton(parent=self.layoutWidget_right)
        self.login_fb.setMinimumSize(QtCore.QSize(0, 38))
        self.login_fb.setStyleSheet("QPushButton{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:5px;background:white;font-size:13px;color:#333;\n"
"}\n"
"QPushButton:hover{background:#fffbf0;}")
        self.login_fb.setObjectName("login_fb")
        self.vLayout_right.addWidget(self.login_fb)
        self.login_apple = QtWidgets.QPushButton(parent=self.layoutWidget_right)
        self.login_apple.setMinimumSize(QtCore.QSize(0, 38))
        self.login_apple.setStyleSheet("QPushButton{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:5px;background:white;font-size:13px;color:#333;\n"
"}\n"
"QPushButton:hover{background:#fffbf0;}")
        self.login_apple.setObjectName("login_apple")
        self.vLayout_right.addWidget(self.login_apple)
        spacerItem1 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_right.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(parent=self.frame_right)
        self.frame.setGeometry(QtCore.QRect(30, 163, 391, 471))
        self.frame.setStyleSheet("QFrame{background-color:white}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.Signup_username = QtWidgets.QLineEdit(parent=self.frame)
        self.Signup_username.setMinimumSize(QtCore.QSize(0, 38))
        self.Signup_username.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.Signup_username.setObjectName("Signup_username")
        self.gridLayout.addWidget(self.Signup_username, 1, 0, 1, 1)
        self.hLayout_emailRow_2 = QtWidgets.QHBoxLayout()
        self.hLayout_emailRow_2.setObjectName("hLayout_emailRow_2")
        self.label_email_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_email_3.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_email_3.setObjectName("label_email_3")
        self.hLayout_emailRow_2.addWidget(self.label_email_3)
        self.noti_email_signup = QtWidgets.QLabel(parent=self.frame)
        self.noti_email_signup.setStyleSheet("QLabel{color:#e53935;font-size:11px;background:transparent;border:none;}")
        self.noti_email_signup.setText("")
        self.noti_email_signup.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.noti_email_signup.setObjectName("noti_email_signup")
        self.hLayout_emailRow_2.addWidget(self.noti_email_signup)
        self.gridLayout.addLayout(self.hLayout_emailRow_2, 2, 0, 1, 3)
        self.enter_password_signup = QtWidgets.QLineEdit(parent=self.frame)
        self.enter_password_signup.setMinimumSize(QtCore.QSize(0, 38))
        self.enter_password_signup.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.enter_password_signup.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.enter_password_signup.setObjectName("enter_password_signup")
        self.gridLayout.addWidget(self.enter_password_signup, 5, 0, 1, 3)
        self.label_forgot_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_forgot_2.setStyleSheet("QLabel{\n"
"    color:#34C759;font-size:11px;background:transparent;\n"
"    border:none;font-weight:bold;\n"
"}")
        self.label_forgot_2.setText("")
        self.label_forgot_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_forgot_2.setObjectName("label_forgot_2")
        self.gridLayout.addWidget(self.label_forgot_2, 6, 0, 1, 1)
        self.enter_email_signup = QtWidgets.QLineEdit(parent=self.frame)
        self.enter_email_signup.setMinimumSize(QtCore.QSize(0, 38))
        self.enter_email_signup.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.enter_email_signup.setObjectName("enter_email_signup")
        self.gridLayout.addWidget(self.enter_email_signup, 3, 0, 1, 3)
        self.btn_Signup_2 = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Signup_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Signup_2.setStyleSheet("QPushButton{\n"
"    background:#34C759;color:white;border-radius:8px;\n"
"    font-weight:bold;font-size:15px;border:none;\n"
"}\n"
"QPushButton:hover{background:#2db34e;}\n"
"QPushButton:pressed{background:#259e45;}")
        self.btn_Signup_2.setObjectName("btn_Signup_2")
        self.gridLayout.addWidget(self.btn_Signup_2, 9, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 16, 1, 1, 1)
        self.label_username_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_username_5.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_username_5.setObjectName("label_username_5")
        self.gridLayout.addWidget(self.label_username_5, 0, 0, 1, 1)
        self.Signup_age = QtWidgets.QLineEdit(parent=self.frame)
        self.Signup_age.setMinimumSize(QtCore.QSize(0, 38))
        self.Signup_age.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.Signup_age.setObjectName("Signup_age")
        self.gridLayout.addWidget(self.Signup_age, 1, 2, 1, 1)
        self.hLayout_pwRow_2 = QtWidgets.QHBoxLayout()
        self.hLayout_pwRow_2.setObjectName("hLayout_pwRow_2")
        self.label_password_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_password_3.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_password_3.setObjectName("label_password_3")
        self.hLayout_pwRow_2.addWidget(self.label_password_3)
        self.noti_password_signup = QtWidgets.QLabel(parent=self.frame)
        self.noti_password_signup.setStyleSheet("QLabel{color:#e53935;font-size:11px;background:transparent;border:none;}")
        self.noti_password_signup.setText("")
        self.noti_password_signup.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.noti_password_signup.setObjectName("noti_password_signup")
        self.hLayout_pwRow_2.addWidget(self.noti_password_signup)
        self.gridLayout.addLayout(self.hLayout_pwRow_2, 4, 0, 1, 3)
        self.label_username_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_username_6.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_username_6.setObjectName("label_username_6")
        self.gridLayout.addWidget(self.label_username_6, 0, 1, 1, 1)
        self.Signup_Pnumber = QtWidgets.QLineEdit(parent=self.frame)
        self.Signup_Pnumber.setMinimumSize(QtCore.QSize(0, 38))
        self.Signup_Pnumber.setStyleSheet("QLineEdit{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:4px 10px;background:white;font-size:13px;color:#555;\n"
"}\n"
"QLineEdit:focus{border:1.5px solid #34C759;}")
        self.Signup_Pnumber.setObjectName("Signup_Pnumber")
        self.gridLayout.addWidget(self.Signup_Pnumber, 1, 1, 1, 1)
        self.label_username_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_username_7.setStyleSheet("QLabel{font-size:13px;background:transparent;border:none;color:#222;}")
        self.label_username_7.setObjectName("label_username_7")
        self.gridLayout.addWidget(self.label_username_7, 0, 2, 1, 1)
        self.label_login1 = QtWidgets.QLabel(parent=self.frame)
        self.label_login1.setStyleSheet("QLabel{font-size:12px;background:transparent;border:none;color:#444;}")
        self.label_login1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_login1.setObjectName("label_login1")
        self.gridLayout.addWidget(self.label_login1, 11, 1, 1, 1)
        self.login_apple_2 = QtWidgets.QPushButton(parent=self.frame)
        self.login_apple_2.setMinimumSize(QtCore.QSize(0, 38))
        self.login_apple_2.setStyleSheet("QPushButton{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:5px;background:white;font-size:13px;color:#333;\n"
"}\n"
"QPushButton:hover{background:#fffbf0;}")
        self.login_apple_2.setObjectName("login_apple_2")
        self.gridLayout.addWidget(self.login_apple_2, 15, 0, 1, 3)
        self.signup_gg_2 = QtWidgets.QPushButton(parent=self.frame)
        self.signup_gg_2.setMinimumSize(QtCore.QSize(0, 38))
        self.signup_gg_2.setStyleSheet("QPushButton{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:5px;background:white;font-size:13px;color:#333;\n"
"}\n"
"QPushButton:hover{background:#fffbf0;}")
        self.signup_gg_2.setObjectName("signup_gg_2")
        self.gridLayout.addWidget(self.signup_gg_2, 13, 0, 1, 3)
        self.hLayout_or_2 = QtWidgets.QHBoxLayout()
        self.hLayout_or_2.setObjectName("hLayout_or_2")
        self.line_left_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_left_2.setStyleSheet("QFrame{color:#ccc;border:none;}")
        self.line_left_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_left_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_left_2.setObjectName("line_left_2")
        self.hLayout_or_2.addWidget(self.line_left_2)
        self.label_or_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_or_2.setStyleSheet("QLabel{color:#888;font-size:12px;padding:0 8px;background:transparent;border:none;}")
        self.label_or_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_or_2.setObjectName("label_or_2")
        self.hLayout_or_2.addWidget(self.label_or_2)
        self.line_right_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_right_2.setStyleSheet("QFrame{color:#ccc;border:none;}")
        self.line_right_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_right_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_right_2.setObjectName("line_right_2")
        self.hLayout_or_2.addWidget(self.line_right_2)
        self.gridLayout.addLayout(self.hLayout_or_2, 12, 1, 1, 1)
        self.login_fb_2 = QtWidgets.QPushButton(parent=self.frame)
        self.login_fb_2.setMinimumSize(QtCore.QSize(0, 38))
        self.login_fb_2.setStyleSheet("QPushButton{\n"
"    border:1.5px solid #FEC300;border-radius:8px;\n"
"    padding:5px;background:white;font-size:13px;color:#333;\n"
"}\n"
"QPushButton:hover{background:#fffbf0;}")
        self.login_fb_2.setObjectName("login_fb_2")
        self.gridLayout.addWidget(self.login_fb_2, 14, 0, 1, 3)
        self.general_noti_signup = QtWidgets.QLabel(parent=self.frame)
        self.general_noti_signup.setStyleSheet("QLabel{color:#e53935;font-size:11px;background:transparent;border:none;}")
        self.general_noti_signup.setText("")
        self.general_noti_signup.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.general_noti_signup.setObjectName("general_noti_signup")
        self.gridLayout.addWidget(self.general_noti_signup, 7, 1, 1, 1)
        self.noti_general_2 = QtWidgets.QLabel(parent=self.frame)
        self.noti_general_2.setStyleSheet("QLabel{\n"
"    color:#e53935;font-size:11px;background:transparent;\n"
"    border:none;\n"
"}")
        self.noti_general_2.setText("")
        self.noti_general_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.noti_general_2.setObjectName("noti_general_2")
        self.gridLayout.addWidget(self.noti_general_2, 8, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_right)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "M3M English"))
        self.label_title_left.setText(_translate("MainWindow", "M3M English"))
        self.label_tagline.setText(_translate("MainWindow", "<div align=\"center\">\n"
"<span style=\"color:#2E7D32;font-size:16px;font-weight:700;\">Learn </span>\n"
"<span style=\"color:#FF4B4B;font-size:16px;font-weight:700;\">1000 words</span><br>\n"
"<span style=\"color:#444;font-size:15px;\">in just </span>\n"
"<span style=\"color:#C9D83B;font-size:15px;font-weight:700;\">30 days!</span>\n"
"</div>"))
        self.label_M3M.setText(_translate("MainWindow", "M3M"))
        self.label_English.setText(_translate("MainWindow", "English"))
        self.btn_Signup.setText(_translate("MainWindow", "Sign up"))
        self.btn_Login.setText(_translate("MainWindow", "Login"))
        self.label_username.setText(_translate("MainWindow", "User name:"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_email.setText(_translate("MainWindow", "Email Address:"))
        self.enter_email.setPlaceholderText(_translate("MainWindow", "m3menglish@gmail.com"))
        self.label_password.setText(_translate("MainWindow", "Password:"))
        self.enter_password.setPlaceholderText(_translate("MainWindow", "m3mstudy"))
        self.btnLogin_Enter.setText(_translate("MainWindow", "Login"))
        self.label_firsttime_full.setText(_translate("MainWindow", "<div align=\"center\">First time to M3M?&nbsp;<span style=\"color:#34c759;font-weight:bold;\">Sign Up</span></div>"))
        self.label_or.setText(_translate("MainWindow", "or"))
        self.login_gg.setText(_translate("MainWindow", "Login with Google"))
        self.login_fb.setText(_translate("MainWindow", "Login with Facebook"))
        self.login_apple.setText(_translate("MainWindow", "Login with Apple"))
        self.Signup_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_email_3.setText(_translate("MainWindow", "Email Address:"))
        self.enter_password_signup.setPlaceholderText(_translate("MainWindow", "m3mstudy"))
        self.enter_email_signup.setPlaceholderText(_translate("MainWindow", "m3menglish@gmail.com"))
        self.btn_Signup_2.setText(_translate("MainWindow", "Sign Up"))
        self.label_username_5.setText(_translate("MainWindow", "User name:"))
        self.Signup_age.setPlaceholderText(_translate("MainWindow", "Age"))
        self.label_password_3.setText(_translate("MainWindow", "Password:"))
        self.label_username_6.setText(_translate("MainWindow", "Phone Number:"))
        self.Signup_Pnumber.setPlaceholderText(_translate("MainWindow", "012345678"))
        self.label_username_7.setText(_translate("MainWindow", "Age:"))
        self.label_login1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Already have an account? <span style=\" font-weight:600; color:#34c759;\">Login</span></p></body></html>"))
        self.login_apple_2.setText(_translate("MainWindow", "Sign up with Apple"))
        self.signup_gg_2.setText(_translate("MainWindow", "Sign up with Google"))
        self.label_or_2.setText(_translate("MainWindow", "or"))
        self.login_fb_2.setText(_translate("MainWindow", "Sign up with Facebook"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
